-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgR6Uakr+3j/iyuSux
fAgWFZb/GHD4xHCDZDUbC+c/eJ6gCgYIKoZIzj0DAQehRANCAAQOXmJXUfZNvE3S
FRvfvazZGMHUal83Rzt7XbgPZJgahH4SCyM97Y8aUMMaGPghVCnRR6RDLKDYlTC6
dhMl6/b0
-----END PRIVATE KEY-----